Feature branch
SarvarKh/TNW-clone pull request #2
Opened 2020-11-05 13:50 UTC by SarvarKh

Responsive web-design | Clone of The Next Web

2020-11-05 16:17 UTC, uryelah commented
Hi  **Gerald Enekwechi & Sarvar Khalimov**! 👋 

I'm marking this Code review request as **INVALID** because this PR(Pull Request) currentl does not meet the standards of a good descriptive title and message.

Please make sure to review the _3 basic rules to follow in Microverse projects_ step at [the professional repo guide from Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) and edit your PR title and message in a way that they are meaningful and descriptive of the code you are submiting.

**Example of a good PR message:**
![69548761-3a8d3600-0f98-11ea-9f19-14da361c12e2](https://user-images.githubusercontent.com/16193212/98266466-1a684400-1f69-11eb-8265-1d5b5e4ccc66.gif)

----

### Please _re-submit_ your project for review after updating the PR message and title accordingly.

2020-11-05 19:49 UTC, uche-inyama requested changes
## Changes Required

### Hi team :wave: 

Your design looks good, however, it would be nice to:

- [x]  Increase the grid size of **Latest deals** and **Latest news** section to 4 grids and 3 grids  @media >=950px and @media >= 800 px respectively.

- [ ] Ensure to use the standard widths while implementing your media queries. These widths are: 

                     // small devices
                    @media (min-width: 576px) { ... }

                      // Medium devices (tablets, 768px and up)
                     @media (min-width: 768px) { ... }

                      // Large devices (desktops, 992px and up)
                      @media (min-width: 992px) { ... }

                       // Extra large devices (large desktops, 1200px and up)
                       @media (min-width: 1200px) { ... }

That's it, make the changes and submit another form for a code review

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

2020-11-05 19:49 UTC, uche-inyama commented on index.html
> +      <!-- Heading -->
Use the main tag to wrap elements within the main section [semantic HTML](https://www.w3schools.com/html/html5_semantic_elements.asp)

2020-11-06 16:23 UTC, MuriloRoque approved these changes
## Status: Approved :green_circle: 

### Hello @SarvarKh and @Oxford-G :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-11-06 16:27 UTC, merged